grafana:
  enabled: true
  adminPassword: "trustusbank-demo"
  service:
    type: ClusterIP
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true
  additionalDataSources:
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo.trustusbank-observability.svc.cluster.local:3200
      access: proxy
      jsonData:
        nodeGraph: { enabled: true }
    - name: Loki
      type: loki
      uid: loki
      url: http://loki.trustusbank-observability.svc.cluster.local:3100
      access: proxy

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 30d

alertmanager:
  enabled: true
