apiVersion: v1
kind: ServiceAccount
metadata:
  name: evil-tools
  namespace: trustusbank-bank-evil
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evil-tools
  namespace: trustusbank-bank-evil
  labels:
    app: evil-tools
    tier: red-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evil-tools
  template:
    metadata:
      labels:
        app: evil-tools
        tier: red-team
    spec:
      serviceAccountName: evil-tools
      containers:
        - name: server
          image: localhost:5001/trustusbank/evil-tools:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.trustusbank-observability.svc.cluster.local:4317
            - name: OTEL_SERVICE_NAME
              value: evil-tools
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
---
apiVersion: v1
kind: Service
metadata:
  name: evil-tools
  namespace: trustusbank-bank-evil
spec:
  selector:
    app: evil-tools
  ports:
    - name: http
      port: 8080
      targetPort: 8080
