apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: account-mcp
  namespace: trustusbank-platform
spec:
  mcp:
    targets:
      - name: account-mcp
        backendRef:
          name: account-mcp
          namespace: trustusbank-bank-mcp
        port: 8080
        protocol: STREAMABLE_HTTP
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: transaction-mcp
  namespace: trustusbank-platform
spec:
  mcp:
    targets:
      - name: transaction-mcp
        backendRef:
          name: transaction-mcp
          namespace: trustusbank-bank-mcp
        port: 8080
        protocol: STREAMABLE_HTTP
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: ticket-mcp
  namespace: trustusbank-platform
spec:
  mcp:
    targets:
      - name: ticket-mcp
        backendRef:
          name: ticket-mcp
          namespace: trustusbank-bank-mcp
        port: 8080
        protocol: STREAMABLE_HTTP
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: evil-tools
  namespace: trustusbank-platform
spec:
  mcp:
    targets:
      - name: evil-tools
        backendRef:
          name: evil-tools
          namespace: trustusbank-bank-evil
        port: 8080
        protocol: STREAMABLE_HTTP
