apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: jwt-validation
  namespace: trustusbank-platform
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: account-mcp-route
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: transaction-mcp-route
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ticket-mcp-route
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: evil-tools-route
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
        - issuer: http://keycloak.trustusbank-platform.svc.cluster.local/realms/trustusbank
          audiences:
            - support-bot
            - fraud-bot
            - triage-bot
          jwks:
            remote:
              url: http://keycloak.trustusbank-platform.svc.cluster.local/realms/trustusbank/protocol/openid-connect/certs
